version: "3"
services:
  backend:
    build: .
    container_name: "backend"
    env_file: .env
    ports:
      - "8000:8000"
  mongo:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodb:/data/db
    ports:
    - "27017:27017"
volumes:
  mongodb: